# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Macros' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Macros
  
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'

  target 'MacrosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MacrosUITests' do
    # Pods for testing
  end

end
